theme: jekyll-theme-minimal
title: Katie Quinlan, CMHC
description: Clinical Director at Sovegna
logo: katie-sovegna.png
sidebar:
  text: >
    [![img](img.jpg)](http://x.com)
    [![img](img.jpg)](http://x.com)
github:
  is_project_page: false
  is_user_page: false
