theme: jekyll-theme-minimal
title: Katie Quinlan, CMHC
description: Clinical Director at Sovegna
logo: katie-sovegna.png
sidebar:
  - title: ""
    image: "https://github.com/katiequinlan/katiequinlan.github.io/assets/96839298/1e992972-b780-4de4-b923-ba58fd77e95b"
  - title: ""
    image: "https://github.com/katiequinlan/katiequinlan.github.io/assets/96839298/07c2861f-919a-474c-b714-c946019bece6"
github:
  is_project_page: false
  is_user_page: false
